### ISSUE TITLE
Expand font source options?

### ISSUE THREAD

**Issue by ikbensiep** [FontManager/font-manager#232] opened 2021-07-28 14:04 UTC
The latest font manager with Google Fonts integration is amazing! Before, I'd use a separate app to browse and download google fonts, so I was delighted to find this feature in Font Manager recently. 

This made me wonder if it would be possible to add more online font resources, ie: dafont.com and other websites at some point in the future. I have no idea if other online font catalogs even offer an API, and this is just an idea I had.

I have not considered alternatives bc this is the best font manager app there is on Ubuntu :)

**Comment by JerryCasiano** [comment] 2021-07-28 19:19
Well, I'm glad you like it. Thanks.

As far as adding other online sources, the issue is whether they have a stable API or not.

Without an API, and preferably a very stable one, it's just not feasible.

If you can link to an API for a particular source please open an issue specific to that source and include the link. I'm happy to look into whether it's something we can add or not.

A lot of commercial sites do provide an API but I'm not really interested in supporting any commercial storefront within the app. I don't think there's enough interest for that to be worthwhile.

I'm closing this for now, but like I said if you do come across any "free" sites that provide an API for access please feel free to open an issue for each.

Thanks for your interest.

**Closed by JerryCasiano** 2021-07-28 19:19 UTC
