### ISSUE TITLE
Filter/group by language support

### ISSUE THREAD

**Issue by alerque** [FontManager/font-manager#56] opened 2018-02-21 12:04 UTC
I do typesetting work in multiple languages. Issue #16 mentions some problems when not working with Latin alphabets, but there is a related issue with Latin scripts as well: namely that not all fonts support all languages. Some kind of character set detection and filtering for what ranges are supported to group by language or custom ranges would be really useful. That way I can look through fonts I have installed that support a specific language that uses extended Latin ranges.

**Comment by JerryCasiano** [comment] 2018-02-21 23:10
Duplicate of #16 

Marking this as duplicate, even though I understand there is a difference, I think the requirements are the same.

While this is definitely a goal of mine, it's not a high priority at this time I'm sorry to say.
That said some improvements that should enable this are already in progress.

Thanks for your interest and suggestion.

**Comment by JerryCasiano** [comment] 2018-06-27 22:07
Reopen.

The changes in the testing branch address issue #16 but do not allow filtering yet.

[testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

**Comment by JerryCasiano** [comment] 2019-03-28 03:28
https://github.com/FontManager/font-manager/tree/language-filter

Is a work in progress which contains some changes that may be of interest to you.

**Comment by JerryCasiano** [comment] 2019-04-08 23:23
Closing this out since these changes have been merged into master.

Please feel free to re-open if this isn't resolved for you.

**Closed by JerryCasiano** 2019-04-08 23:23 UTC
