### ISSUE TITLE
Some fonts are not recognised, but will display if opened via Nemo file manager

### ISSUE THREAD

**Issue by Windsurfer01** [FontManager/font-manager#335] opened 2023-10-03 19:52 UTC
**Describe the bug**
This applies to fonts developed in FontForge.
Some fonts are recognised and opened. Others are not.
Some fonts are displayed in Preview, but not in Characters.
Some fonts will display the characters in Character if opened via Nemo, but not directly by FontManager.

**To Reproduce**
Steps to reproduce the behaviour:
Install the attached font files.
Try opening them in the various ways described above.
[examples.zip](https://github.com/FontManager/font-manager/files/12796495/examples.zip)

**Expected behaviour**
FontManager displays them correctly.

**System Information**
Kernel: 5.15.0-84-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

 - Font Manager version 0.8.8 downloaded from Github

**Comment by Windsurfer01** [comment] 2023-10-03 19:53
I can provide files that exhibit all of the stated characteristics.

**Comment by JerryCasiano** [comment] 2024-03-28 23:15
Apologize for such a late response.

Yeah, the fonts you provided do not work right with the GTK 3 version though for some reason they do work just fine in the GTK 4 version in the work in progress branch.

So the issue is "fixed" I guess, though I'm not sure what we're doing differently. Unfortunately it will be a while before the work in progress version releases so this will remain open until then. 

If you have other font files that have the same issue attaching them here would be appreciated so that I can test with them also.

Thanks for reporting this and again sorry for such a late response.

**Comment by Windsurfer01** [comment] 2024-03-29 06:21
No worries, thanks for the update!

**Comment by JerryCasiano** [comment] 2024-06-16 05:42
I'm closing this out now as the GTK 4 port is now in master. 

Feel free to reopen if this is still an issue.

**Closed by JerryCasiano** 2024-06-16 05:42 UTC
