### ISSUE TITLE
Auto scrolling back to the top, after dragging into a collection

### ISSUE THREAD

**Issue by Pascalio** [FontManager/font-manager#220] opened 2021-06-24 20:31 UTC
**Describe the bug**
In Manage view, the scroll position is set back to the beginning of the list, after dragging any font into a collection on the left-hand pane.

**To Reproduce**
1. In Manage view, scroll down a bit to make it obvious
2. make sure you have some collection on the left-hand pane
3. drag any font into a collection
4. the view goes back to the top...

**Expected behavior**
Expected behaviour would be for the view to keep the scroll position.
It would actually be awesome if the scroll position could be retained for each collection or category, so that you can jump from one to the other and land back where you left it.

**System Information**
 - OS: Kubuntu 20.04
 - KDE
 - Font Manager version 0.8.6

**Comment by JerryCasiano** [comment] 2021-06-25 02:54
The latest commit should restore the font list to the same position it was in when the drag started.

Thanks for pointing this out.. 

> It would actually be awesome if the scroll position could be retained for each collection or category, so that you can jump from one to the other and land back where you left it.

I'm not so sure this is a good idea.

It would mean listening to every scroll event and storing the current position for each individual category or collection. Categories are not static since they're dynamically generated so we'll likely end up doing the wrong thing at random times. 


But I could be wrong so I'll leave this open for now in case I get a chance to try it and see how it works in practice.

**Comment by JerryCasiano** [comment] 2021-07-20 00:23
@Pascalio 
@PF4Public 

I've added a branch which tracks filter selections and restores them.

I didn't push it to master because I'm not really sure how I feel about it, I think it's OK, maybe even an improvement.

If you guys prefer it I'm happy to merge it into master. Let me know.

Also not sure if we should save this across restarts or not, though I'm leaning towards not saving it right now.

**Comment by PF4Public** [comment] 2021-07-20 09:17
@JerryCasiano Honestly saying, I don't use collections, marked this issue with thumbs-up as it may interfere with user actions, which is a nuisance in my opinion. But if you wish this feature to be tested by someone except you, I can do it later this week.

**Comment by JerryCasiano** [comment] 2021-07-20 13:02
@PF4Public 

Yeah, whenever you get a chance checkout that branch. I'd appreciate any feedback.

It's the second part of the suggestion where your selections are restored as you move thorough different categories. So for example if you were viewing Noto in the All category and switched to a different category switching back to All should reselect Noto for you.

Just trying to make sure it works as expected in the majority of cases. I can see it becoming confusing to users if it doesn't and ends up making random selections.

**Comment by PF4Public** [comment] 2021-07-23 13:45
@JerryCasiano I've built `save-list-state` branch and have some feedback for you :)

At its present state it is fragile, I'd say :D

I select a font in _All_, then go into a _collection_, then go back to _All_ again and exactly that very font gets reselected and the view got scrolled to it. So far so good.

Being a person, who likes breaking things I do just that now (would you mind? ;) ):
I select "Cham" in _All_, go to my _first collection_ and select "Sharada" there, then do to a _second_ one and select "Limbu" there. What should happen If I return to _All_ now? What happens is that it is scrolled to the top. My _first collection_ holds "Sharada" and the _second_ one also got scrolled to the top. Yay :)

I tried different random (not truly random of-course) things and managed to have selection preserved for the second collection as well (everything else was scrolled to the top). There are ways in which _All_ position got saved, but this specific order of selection breaks it in 100% tries. This is obviously not what you intended, right? Would it be an improvement if saving the position of every collection? This misbehaviour shows that it is possible to save positions of collections!

Apart from that I have other things to mention:
* Renaming a collection is a hard task as whenever one clicks the collection's name, for a fraction of a second it shows edit field, which disappears immediately. I had to brute-click it to have the edit field at my disposal.
* It is not very intuitive, that one should press Enter to save changes: I was clicking outside this edit field to finish editing, but nothing was happening.

**Comment by JerryCasiano** [comment] 2021-07-23 23:25
Try the latest whenever you get a chance.

The selection, or re-selection, issue should be good now, I think.

Thanks for pointing out the collection renaming issue! It can be finicky sometimes. I guess I tend to stick to the initial name and never really run into this but definitely an issue. I added an entry to the right click menu for renaming collections. Hopefully this works right...

Thanks!

**Comment by PF4Public** [comment] 2021-07-24 23:29
> The selection, or re-selection, issue should be good now, I think.

It is! Every category now saves its selection including collections. It does not conserve multiselection, but I doubt it is of any importance. (Yeah, I tried to break it with multiselection ;) )

Also the last commit in that branch makes the view even more neat! Compare:
![image](https://user-images.githubusercontent.com/10319700/126883180-6136de6a-91c3-4faf-bc0e-0290f9316b43.png)
![image](https://user-images.githubusercontent.com/10319700/126883185-67c11aaf-f9d9-4a1e-9ae9-579e8558c781.png)

**Comment by JerryCasiano** [comment] 2021-07-25 18:47
@PF4Public 

Thanks for testing!

I'll close this issue in a bit.

Just FYI I plan on doing a release soon. Probably towards the end of this week. I've been putting it off for a while but I'm fairly certain #213 will start affecting users soon if it isn't already.

**Comment by JerryCasiano** [comment] 2021-07-25 19:05
Closing as the changes are now in master.

Feel free to re-open if the issue is not resolved.

Thanks.

**Closed by JerryCasiano** 2021-07-25 19:05 UTC
