### ISSUE TITLE
Display is cut off on left pane

### ISSUE THREAD

**Issue by apcrcom** [FontManager/font-manager#104] opened 2019-12-12 12:13 UTC
MX linux 19 (xfce)

https://i.imgur.com/LWWCIg9.png

**Comment by JerryCasiano** [comment] 2019-12-12 16:32
Duplicate of #101 

Feel free to re-open if the comments in that issue don't apply to you.

Also, looks like you are using a pretty outdated version of the application.

**Closed** 2019-12-12 16:32 UTC
Labels: duplicate, invalid
