### ISSUE TITLE
Preview of Google Fonts doesn't work

### ISSUE THREAD

**Issue by linuxundich** [FontManager/font-manager#135] opened 2020-11-26 16:46 UTC
I installed Font Manager 0.8.0 from AUR under Arch Linux. I'm able to browse and install Google fonts into my system, but the preview mode inside Font Manager always shows a standard font and note the selected Google font. Please to a look at the attached screenshot.

![gnome-shell-screenshot-XG69T0](https://user-images.githubusercontent.com/1716643/100375995-07e4a600-300f-11eb-9727-49c9f447442a.png)

**Comment by JerryCasiano** [comment] 2020-11-26 18:29
Can't reproduce here...

![Screenshot from 2020-11-26 13-25-57](https://user-images.githubusercontent.com/11490124/100383164-fdb0b080-2fea-11eb-81ee-5deb2db90ad3.png)

Are there any warnings when run from a terminal?

**Comment by linuxundich** [comment] 2020-11-26 19:33
> Are there any warnings when run from a terminal?

No, is there a way to activate debug output?

**Comment by JerryCasiano** [comment] 2020-11-26 20:10
Not really, not at this point. :-/

I'll implement some debug output for the WebView over the weekend.

**Comment by JerryCasiano** [comment] 2020-11-27 04:47
Please build from master, run from terminal and post any output that includes warnings in it.

**Comment by linuxundich** [comment] 2020-11-27 09:43
Hi Jerry,

i built Font Manager from master... https://pastebin.com/rEbuAThq

```
$ git clone https://github.com/FontManager/font-manager.git
$ cd font-manager/
$ meson --prefix=/usr --buildtype=release build
$ cd build
$ ninja
$ src/font-manager/font-manager
```
...but I still don't get any messages while running it, even when I try to view the Google fonts.

**Comment by JerryCasiano** [comment] 2020-11-27 22:15
Please remove the build directory then checkout the "debug" branch, i.e.

```
rm -rf build
git fetch
git checkout google-fonts-debug
```

Build the application again and run it, this time you should see output whenever you select a font in the Google Fonts list, after selecting a few fonts please post the output.

Thanks.

**Comment by JerryCasiano** [comment] 2020-11-28 17:23
I suspect this is related to #138 and therefore resolved by the same commit.

Feel free to re-open if that is not the case.

**Closed by JerryCasiano** 2020-11-28 17:23 UTC
