### ISSUE TITLE
Cosmetic issues with the UI

### ISSUE THREAD

**Issue by PF4Public** [FontManager/font-manager#210] opened 2021-03-27 16:02 UTC
@JerryCasiano get ready for some bugs :D
1. Even though I have enabled "wide layout", every time a new version comes, it reverts to non-wide layout. Only toggling that option fixes it.
2. Don't know for how long, but for me one icon is missing (marked with arrow):
![scr](https://user-images.githubusercontent.com/10319700/112726428-7d657200-8f2e-11eb-9b16-fdb3a539e4ab.png)

**Comment by JerryCasiano** [comment] 2021-03-27 16:17
Lol. Well here come some questions.

So for number 1, you have it set to wide layout at all times?  And it reverts to only when maximized with each update? Is that right?

For the second one, which icon themes do you have installed?

I've seen stuff like this in other screenshots, sometimes wrong icons used, same icon used multiple times, etc.

I've considered going through and shipping all the icons we use in the resource file or depending on an icon theme, i.e. adwaita

I've also seen some screenshots with really broken themes so I've actually considered shipping the theme I use in the resource...

Not sure which option is best though?

Respecting the users theme choice and letting it look broken or shipping our choices and let the user break it themselves in our preferences dialog.

**Comment by PF4Public** [comment] 2021-03-27 17:02
> So for number 1, you have it set to wide layout at all times? And it reverts to only when maximized with each update? Is that right?

"only when maximized" is unchecked, so it might be that _this_ option gets ignored upon each update instead of "use wide layout" — cannot tell for sure, but looks probable.

Tried restarting font-manager. Hmmm, I remember the layout thing was usually fixed after toggling untill new release, but not any more. It is fixed only in runtime, and after restarting font-manager, it is still not wide.

>Respecting the users theme choice and letting it look broken or shipping our choices and let the user break it themselves in our preferences dialog.

From the user perspective a theme and an icon-set are mere a theme and an icon-set, user chooses them based on their look, having no idea on the brokenness. But anyway I see the struggle, tough choise it is. My opinion would be that if icons you prefer are freely available and the license allows you to ship them having an option to use either "shipped" or "local" icons would make for a good compromise. Or maybe some fallback mechanism?

>which icon themes do you have installed?

Not many actually:
![image](https://user-images.githubusercontent.com/10319700/112727297-fb2b7c80-8f32-11eb-9e48-3f3d4ef87c39.png)

**Comment by JerryCasiano** [comment] 2021-03-27 20:59
> Or maybe some fallback mechanism?

GTK does have some priority settings for theming but I haven't checked them out in practice.

Will have to play with this and see what the results are.

The preferences not sticking is a priority though, didn't realize it was broken.

**Comment by JerryCasiano** [comment] 2021-03-29 22:30
Looks like we weren't updating the layout at startup, so I think that's fixed with the latest commit.

**Comment by PF4Public** [comment] 2021-03-30 16:11
Gave it a try and the wide layout is now restored upon start. One can notice, that for a moment it is not wide, but fixes itself real quick. This is probbaly completely insignificant and could be ignored.

Another nitpic that I always forget to ask. Is it possible to hide long font names behind ellipsis and stick "variants" labels to the right? Otherwise it looks a bit off, if one has a long name in the list:
![image](https://user-images.githubusercontent.com/10319700/113019256-1217dc00-918a-11eb-9547-f77b6e007941.png)
Also you seem to have a predefined (proportional?) size for the middle column, which is restored upon start and this results in the situation on the screenshot above. Can't tell if this could/should be fixed. Just a little annoyance.

Now that the first issue has been dealt with, what would be your verdict on the second one? I have a feeling, that you tend to close issues that you don't plan working on.

**Comment by JerryCasiano** [comment] 2021-03-30 21:10
> Another nitpic that I always forget to ask. Is it possible to hide long font names behind ellipsis and stick "variants" labels to the right? Otherwise it looks a bit off, if one has a long name in the list:

We can definitely set the family name column to ellipsize at the end, if it's not set to do that.

> Also you seem to have a predefined (proportional?) size for the middle column ...

I don't think so. I avoid setting any sizes anywhere as much as possible as it tends to have weird side effects.

I don't know that there's much we can do as far as the middle column goes. Since it holds previews for fonts the size will vary from row to row. GtkTreeView does allow setting every row to the same height but that causes weird rendering glitches since font previews are not all the same size, I tried that before.

I think we can wrap the pane though and make the counters on the right stay in place the way we do with the sidebar. I'll see if that works.

> Now that the first issue has been dealt with, what would be your verdict on the second one? 

I'm thinking we'll end up shipping any icons we use in the resource file and preferring those over the system theme with the option in preferences to use the system theme. Since most of the icons we use are symbolic anyway I don't think it'll bother anyone and if it does they can toggle the option in settings.

I just need to find them all and gather them up.

> I have a feeling, that you tend to close issues that you don't plan working on.

Yeah, no sense in giving anyone false hope or leaving them open for a decade if you have no plans to actually do anything about it Being a FOSS project means it could be years before anyone gets around to it but if it's open it should mean there is still hope for it.

But that's for feature requests or enhancements, valid bugs stay until they're actually fixed.

**Comment by PF4Public** [comment] 2021-03-30 22:01
> Yeah, no sense in giving anyone false hope or leaving them open for a decade if you have no plans to actually do anything about it Being a FOSS project means it could be years before anyone gets around to it but if it's open it should mean there is still hope for it.

Understandable. My intention with that question was that this bug could be either closed if you have no plans for it, or could be marked as enhancement instead and kept open, while you're figuring your plans on the other points.

**Comment by JerryCasiano** [comment] 2021-04-06 16:28
@PF4Public 

So I packed the icons into the resource we use. I guess the question now becomes does it actually work right. 

When you get a chance to test with master let me know what you see. Does it fix the missing icon and does it break anything for you.

**Comment by PF4Public** [comment] 2021-04-08 17:16
Hi, @JerryCasiano 

I've rebuilt font-manager from master, and see no difference whatsoever:
![image](https://user-images.githubusercontent.com/10319700/114068405-8ea36c80-98a6-11eb-81e5-ba1f3a4aab17.png)

I've checked the contents of a package and see no icons there:
```
~ $ equery f font-manager
 * Searching for font-manager ...
 * Contents of app-misc/font-manager-9999:
/usr
/usr/bin
/usr/bin/font-manager
/usr/lib64
/usr/lib64/font-manager
/usr/lib64/font-manager/libfontmanager.so -> libfontmanager.so.0
/usr/lib64/font-manager/libfontmanager.so.0 -> libfontmanager.so.0.8.5
/usr/lib64/font-manager/libfontmanager.so.0.8.5
/usr/lib64/thunarx-3
/usr/lib64/thunarx-3/thunar-font-manager.so
/usr/libexec
/usr/libexec/font-manager
/usr/libexec/font-manager/font-viewer
/usr/share
/usr/share/applications
/usr/share/applications/org.gnome.FontManager.desktop
/usr/share/applications/org.gnome.FontViewer.desktop
/usr/share/dbus-1
/usr/share/dbus-1/services
/usr/share/dbus-1/services/org.gnome.FontManager.service
/usr/share/dbus-1/services/org.gnome.FontViewer.service
/usr/share/doc
/usr/share/doc/font-manager-9999
/usr/share/doc/font-manager-9999/CHANGELOG.xz
/usr/share/doc/font-manager-9999/README.md.xz
/usr/share/doc/font-manager-9999/README.ro.md.xz
/usr/share/glib-2.0
/usr/share/glib-2.0/schemas
/usr/share/glib-2.0/schemas/org.gnome.FontManager.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.FontViewer.gschema.xml
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/128x128
/usr/share/icons/hicolor/128x128/apps
/usr/share/icons/hicolor/128x128/apps/org.gnome.FontManager.png
/usr/share/icons/hicolor/128x128/apps/org.gnome.FontViewer.png
/usr/share/icons/hicolor/256x256
/usr/share/icons/hicolor/256x256/apps
/usr/share/icons/hicolor/256x256/apps/org.gnome.FontManager.png
/usr/share/icons/hicolor/256x256/apps/org.gnome.FontViewer.png
/usr/share/locale
/usr/share/locale/am
/usr/share/locale/am/LC_MESSAGES
/usr/share/locale/am/LC_MESSAGES/font-manager.mo
/usr/share/locale/ar
/usr/share/locale/ar/LC_MESSAGES
/usr/share/locale/ar/LC_MESSAGES/font-manager.mo
/usr/share/locale/ca
/usr/share/locale/ca/LC_MESSAGES
/usr/share/locale/ca/LC_MESSAGES/font-manager.mo
/usr/share/locale/de
/usr/share/locale/de/LC_MESSAGES
/usr/share/locale/de/LC_MESSAGES/font-manager.mo
/usr/share/locale/es
/usr/share/locale/es/LC_MESSAGES
/usr/share/locale/es/LC_MESSAGES/font-manager.mo
/usr/share/locale/fr
/usr/share/locale/fr/LC_MESSAGES
/usr/share/locale/fr/LC_MESSAGES/font-manager.mo
/usr/share/locale/hr
/usr/share/locale/hr/LC_MESSAGES
/usr/share/locale/hr/LC_MESSAGES/font-manager.mo
/usr/share/locale/ja
/usr/share/locale/ja/LC_MESSAGES
/usr/share/locale/ja/LC_MESSAGES/font-manager.mo
/usr/share/locale/nb_NO
/usr/share/locale/nb_NO/LC_MESSAGES
/usr/share/locale/nb_NO/LC_MESSAGES/font-manager.mo
/usr/share/locale/nl
/usr/share/locale/nl/LC_MESSAGES
/usr/share/locale/nl/LC_MESSAGES/font-manager.mo
/usr/share/locale/oc
/usr/share/locale/oc/LC_MESSAGES
/usr/share/locale/oc/LC_MESSAGES/font-manager.mo
/usr/share/locale/pl
/usr/share/locale/pl/LC_MESSAGES
/usr/share/locale/pl/LC_MESSAGES/font-manager.mo
/usr/share/locale/pt_BR
/usr/share/locale/pt_BR/LC_MESSAGES
/usr/share/locale/pt_BR/LC_MESSAGES/font-manager.mo
/usr/share/locale/ro
/usr/share/locale/ro/LC_MESSAGES
/usr/share/locale/ro/LC_MESSAGES/font-manager.mo
/usr/share/locale/ru
/usr/share/locale/ru/LC_MESSAGES
/usr/share/locale/ru/LC_MESSAGES/font-manager.mo
/usr/share/locale/sl
/usr/share/locale/sl/LC_MESSAGES
/usr/share/locale/sl/LC_MESSAGES/font-manager.mo
/usr/share/locale/sv
/usr/share/locale/sv/LC_MESSAGES
/usr/share/locale/sv/LC_MESSAGES/font-manager.mo
/usr/share/locale/uk
/usr/share/locale/uk/LC_MESSAGES
/usr/share/locale/uk/LC_MESSAGES/font-manager.mo
/usr/share/locale/zh_CN
/usr/share/locale/zh_CN/LC_MESSAGES
/usr/share/locale/zh_CN/LC_MESSAGES/font-manager.mo
/usr/share/locale/zh_HK
/usr/share/locale/zh_HK/LC_MESSAGES
/usr/share/locale/zh_HK/LC_MESSAGES/font-manager.mo
/usr/share/locale/zh_TW
/usr/share/locale/zh_TW/LC_MESSAGES
/usr/share/locale/zh_TW/LC_MESSAGES/font-manager.mo
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/font-manager.1.xz
/usr/share/metainfo
/usr/share/metainfo/org.gnome.FontManager.appdata.xml
/usr/share/metainfo/org.gnome.FontViewer.appdata.xml
```

Do I need to pass a flag to meson for it to copy icons?

**Comment by JerryCasiano** [comment] 2021-04-08 22:56
> Do I need to pass a flag to meson for it to copy icons?

Nope. The icons actually get compiled into the binary.  They're listed in lib/common/gresources.xml, anything listed there gets turned into C code and compiled into the binary.

The path was wrong though, I just fixed that so when you get a chance try again.

You can see if the icons actually got compiled in by using the GTK Inspector. Ctrl + Shift + I should open it, may have to be enabled on your system, then under the resources tab you should see them listed if you scroll down.

**Comment by PF4Public** [comment] 2021-04-09 20:37
Still no changes (sorry for the german UI):
![image](https://user-images.githubusercontent.com/10319700/114237334-9e48b100-998b-11eb-9041-398b7566d026.png)

Ellipsing keeps a lot of free space in the middle. Compare these screenshots:
![image](https://user-images.githubusercontent.com/10319700/114237670-13b48180-998c-11eb-9f7d-5fb65981f268.png)
![image](https://user-images.githubusercontent.com/10319700/114237711-216a0700-998c-11eb-9811-7e84f8208883.png)
![image](https://user-images.githubusercontent.com/10319700/114237762-32b31380-998c-11eb-846a-a25474b8423f.png)

**Comment by JerryCasiano** [comment] 2021-04-09 21:12
Well I'm not sure why the icons aren't being used, according to the docs they should be.

Can you what the icon theme you're using ships for "edit-symbolic"?

> Ellipsing keeps a lot of free space in the middle.

Is that better or worse?

**Comment by PF4Public** [comment] 2021-04-10 16:13
> Is that better or worse?
> 
> I don't think there's any way to control where it gets cut off.

I think, I see, what is happening here. You're creating 4 columns here:
https://github.com/FontManager/font-manager/blob/fe5ea2d729519881606f3f38c5ee7be173f30046/src/font-manager/FontList.vala#L119-L122
Each occupying own space:
![image](https://user-images.githubusercontent.com/10319700/114275936-0c918000-9a2d-11eb-90b2-34cdf5ab6f99.png)
I think they should be separted, so that `FontListColumn.TOGGLE`, `FontListColumn.TEXT` and `FontListColumn.COUNT` being created as a single row, while `FontListColumn.TEXT` and `FontListColumn.PREVIEW` following them and occupying everything below them.

As a side note, huge space is partially due to `FontListColumn.COUNT` allowed to expand. Disallowing like this:
```c
get_column(i).expand = (i != FontListColumn.TOGGLE && i != FontListColumn.COUNT);
```
improves the situation:
![image](https://user-images.githubusercontent.com/10319700/114276184-38f9cc00-9a2e-11eb-83b2-6f4e7a908ea1.png)

But it is still far from perfect: "EB Garamond 12…" gets cut.

Ideally `checkbox`, `font-name` and `count` should share a line, while `count` and `checkbox` being width-fixed, allowing `font-name` to expand. `Variants' names` with `previews` should go as an array of a separate lines below, enjoing greater space without the `checkbox` and the `count`.

> Can you what the icon theme you're using ships for "edit-symbolic"?

Are you asking for an icon name, which gets returned by a system for "edit-symbolic"? How do I obtain that? Is there a query commandline tool for that?

**Comment by JerryCasiano** [comment] 2021-04-10 17:54
> As a side note, huge space is partially due to FontListColumn.COUNT allowed to expand.

I'll try that combination. Thanks.

I tried a few different combinations but most of them had some unfortunate side effects.

> Ideally checkbox, font-name and count should share a line, while count and checkbox being width-fixed, allowing font-name to expand. Variants' names with previews should go as an array of a separate lines below, enjoing greater space without the checkbox and the count.

Unfortunately that's not how treeviews work. With a treeview you define columns and every row has the same columns, you can't have only certain columns in certain rows, you can hide the ones that aren't needed or show different columns but they're always there in every row and sometimes affect sizing even when hidden.

As far as making certain columns fixed width goes that would maybe work ok for the checkbox column but it falls apart quickly anytime there is text involved unless you hardcode font and size.

BUT you did just give an idea, if we can check whether rows are visible and only populate preview rows when they're actually visible that would probably help not only this issue but also performance, I don't know if that's possible though I need to check.

**Comment by hosiet** [comment] 2021-04-11 03:35
Hi @JerryCasiano , I just noticed that many icons are embedded in the recent updates of font-manager.

I'm just wondering about where those icons came from and whether they are compatible with GPL-3.0 used by font-manager. My raw guess is that they come from `adwaita-icon-theme`, in which case we need to document the copyright information as well as the license for the icons somewhere (CC-BY-SA-3.0 or LGPL-3).

**Comment by JerryCasiano** [comment] 2021-04-11 04:16
@hosiet 

Thanks for bringing this up. Definitely an important consideration.

> My raw guess is that they come from adwaita-icon-theme, 

That would be a correct guess.

> in which case we need to document the copyright information as well as the license for the icons somewhere (CC-BY-SA-3.0 or LGPL-3).

I'm not clear on whether we rally need to or not actually...

Seems like this use would fall under modified versions? which does allow simply shipping under the GPL.

BUT since these are icons as opposed to code it's not really clear cut.

Right now though it seems as though that commit will probably just be reverted since it doesn't seem to solve the issue with missing icons anyway. Compiling a bunch of icons that aren't actually used anywhere into the program is not something I really want to do.

If we do keep them, we'll have to do whatever is needed to be compliant, that's for sure.

**Comment by JerryCasiano** [comment] 2021-04-11 04:28
@PF4Public 

> Are you asking for an icon name, which gets returned by a system for "edit-symbolic"? How do I obtain that? Is there a query commandline tool for that?

No command line tool that I know of.

You can use gtk3-icon-browser, should already be installed, and search for it to see what shows up for that icon.

If it shows a missing icon image then something is wrong, your adwaita installation is missing icons. If it shows an icon instead of the missing icon image then the problem is with the icon theme you're using.

Faenza is pretty old though (pre-Adwaita) so it might be declaring a dependency on an icon theme that no longer exists.

**Comment by PF4Public** [comment] 2021-04-11 10:47
🎉 The icon is fixed now:
![image](https://user-images.githubusercontent.com/10319700/114301091-d0f9c300-9acb-11eb-96ba-3d1b41021721.png)


> With a treeview you define columns and every row has the same columns, you can't have only certain columns in certain rows, you can hide the ones that aren't needed or show different columns but they're always there in every row and sometimes affect sizing even when hidden.

Is it possible for a cell to expand if the next one is empty?

**Comment by JerryCasiano** [comment] 2021-04-11 13:42
@PF4Public 

> The icon is fixed now:

Can't believe I didn't catch it earlier... 🤦 

> Is it possible for a cell to expand if the next one is empty?

It doesn't appear to work that way. It seems as though the treeview reserves some space for it anyway. You can see this in the child rows, even though the checkbox column is hidden the width of it is still there it's just that the widget isn't rendered.

Right now whenever rows are not expanded we're setting the preview column to an empty string and hiding it but it still takes up space.

**Comment by PF4Public** [comment] 2021-05-29 09:47
> It doesn't appear to work that way. It seems as though the treeview reserves some space for it anyway. You can see this in the child rows, even though the checkbox column is hidden the width of it is still there it's just that the widget isn't rendered.

By any chance could it be implemented via some custom widget(-s)? There must be some way to do this :)

**Comment by JerryCasiano** [comment] 2021-05-29 17:56
Yes and no.

We can use a ListBox and custom widgets where we would have full control over their appearance, spacing, etc.

But I don't believe we can do that in a way that wouldn't have a significant impact on performance.

On the bright side, if or when we move to GTK 4 or 5 we can get this for free since TreeView is looking like it'll be deprecated and the new lists in GTK 4 only render visible widgets which are cached and updated as you scroll.

**Comment by PF4Public** [comment] 2021-05-29 18:48
> if or when we move to GTK 4 or 5

I suppose, this is not happening in the near feature though…

**Comment by JerryCasiano** [comment] 2021-05-29 22:21
No, unfortunately not anytime soon.

GTK 4 brings a ton of changes, porting to GTK 4 is not going to be quick and easy, it *may* happen once it's stable but, and this is a big but, the devs are already talking about GTK 5 so... Kind of wait and see at this point.

BTW I started porting to GTK 4 early on and hit a LOT of bugs and the rate of change was just too much, the code was constantly broken, I'll definitely revisit it once they consider it stable but if they plan on making 5 as breaking as 4 and releasing it back to back we, and I'm guessing a lot of other  applications will probably end up skipping 4. That kind of churn just doesn't make sense.

So hopefully what they have planned for GTK 5 is more evolutionary than revolutionary.

**Comment by JerryCasiano** [comment] 2021-05-30 00:46
Oh, I also don't know what the status is on [WebKit](https://bugs.webkit.org/show_bug.cgi?id=210100), that issue is still open not sure if any releases actually support GTK 4 yet. 

That was or is a blocker for us though, removing features is not an option in my opinion.

**Comment by JerryCasiano** [comment] 2022-02-20 17:54
@PF4Public 

When you get a chance check out the [testing-210](https://github.com/FontManager/font-manager/tree/testing-210) branch and see if that change results in what you were hoping for.

**Comment by PF4Public** [comment] 2022-02-21 19:41
Wonderful! You did it! It is exactly how I imagined it ought to function. The only nitpick is that checkboxes and text jump a little upon expanding (see the video at the end). But nonetheless it is sufficiently neat so this visual glitch could be ignored.

https://user-images.githubusercontent.com/10319700/155014693-9a6ff059-55be-484e-af9c-dc6cf8c19fad.mp4

**Comment by JerryCasiano** [comment] 2022-02-21 20:26
Alright. Sounds good, I'll merge and put this one to bed later tonight.

Sorry, I was hesitant to do it this way due to the fact that now you can't readily see the style name but honestly don't think it matters anymore since we now seem to render something sane in the majority of cases.

**Comment by PF4Public** [comment] 2022-02-21 20:47
> you can't readily see the style name

That's harmless for the most part I think.

I guess this was the last one of "cosmetic issues", feel free to close this issue when you merge that branch.

**Closed** 2022-02-22 03:46 UTC
Labels: enhancement
