### ISSUE TITLE
[Feature suggestion] Support more online font sources

### ISSUE THREAD

**Issue by noyannus** [FontManager/font-manager#313] opened 2023-03-18 18:01 UTC
I was delighted to find Font Manager today and it sent me dreaming....

It would be very useful (saving time and clicks for many) to have internet sources available in the same way as Google.

As sources consider for example:
- the various distro's package managers (which of their GUIs allow filtering and previews?),
- [dafont.com](https://www.dafont.com/)  ("either freeware, shareware, demo versions or public domain"),
- [CTAN](https://www.ctan.org/) (Comprehensive TeX Archive Network) [(fonts here)](https://www.ctan.org/search?phrase=fonts&ext=true&_PKG=&PKG=on&_AUTHORS=&AUTHORS=on&_TOPICS=&TOPICS=on&_FILES=&_PORTAL=&PORTAL=on&wildcard=on&max=256)

Researching the best web font sources and making them available via toolbar button is a huge undertaking even for the most diligent developer. But an option to enter an arbitrary URL with a placeholder for one or more search term(s) could be feasible, I guess. 
Like,
```
%FONTNAME% 	font name
%AUTH% 		author/maintainer
%LUPD%		last update
%THEME%		font theme
...
```
Probably it's not useful to predefine named tokens as above, because of the endless variety of data fields offered by the fonts sites to search. Instead, plain (unlimited) numbers would allow the user to map the fields themselves.

(Later, a wiki or discussion page could host a collection of (user-provided) search presets.)

E.g., the user has set this in a config file or in a GUI equivalent:
```
NAME	URL
CTAN	https://www.ctan.org/search?phrase=%1%&ext=true&_PKG=&PKG=on&_AUTHORS=%2%&AUTHORS=on&_TOPICS=&TOPICS=on&_FILES=&_PORTAL=&PORTAL=on&wildcard=on&max=256`

TOKEN	MEANING
%1%		font name
%2%		author/maintainer
```

After they entered "Charter" into the field that replaces %1% with its content, the server is queried with:
```
https://www.ctan.org/search?phrase=Charter&ext=true&_PKG=&PKG=on&_AUTHORS=&AUTHORS=on&_TOPICS=&TOPICS=on&_FILES=&_PORTAL=&PORTAL=on&wildcard=on&max=256
```

Note that the author token has been removed because that field was not filled.
Text fields would have to auto-match in number the set preference tokens and the labels the respective names.

**Comment by JerryCasiano** [comment] 2023-03-19 00:50
So this is actually a duplicate of Issue #232, my response in that issue still applies so I would suggest you take a look.

I'll address some issues with your suggestions here but I am closing this as a duplicate.

There is no specification that's used across distributions that would allow for this type of feature. 
gnome-software has tried and so far has not been successful in my experience - the font section is always broken in some way. 

Adding distro specific kludges to workaround anything is a non-starter, even for the ones I use...

As far as sites such as dafont.com that's covered in #232, they don't provide any kind of API that I'm aware of. The fact they mix "free" and proprietary fonts, at least last time I checked, is also an issue. Supporting commercial sites is not a goal at this time.

CTAN is simply not a usable source. The "fonts" they serve may or may not contain anything that can be used by GTK applications in the package and there is no way to know, no way to preview anything, no consistency.


Thanks for you interest and if you do happen to come across an online source that is established, has an actual API and serves free fonts please feel free to open a new issue so we can discuss adding it.

I would be happy to add sources other than Google but it has to be maintainable in the long term. Hacks that can and likely will break with any changes to the site are not something I'm interested in maintaining at all.

**Closed by JerryCasiano** 2023-03-19 00:51 UTC
Labels: duplicate

**Comment by noyannus** [comment] 2023-03-19 11:20
Thank you for the quick reply and the in depth explanations. Have a good Sunday!
