### ISSUE TITLE
"Network offline" error when attempting to use Google Fonts (flatpak 0.8)

### ISSUE THREAD

**Issue by mrmatteastwood** [FontManager/font-manager#153] opened 2020-11-30 11:47 UTC
**Steps to Reproduce:**
1. Install Font Manager 0.8 from flathub on Linux Mint 20 on a PC connected to the Internet
2. Run Font Manager
3. Click "G" button

**Current Results:**
When clicking the "G" button to access Google Fonts, the following error message appears:

Network Offline
An active internet connection is required to access the Google Fonts catalog

**Expected Results:**
Font Manager should be able to access Google Fonts on a computer that is connected to the Internet.

**Notes:**
System specs of the PCs on which this bug was encountered:
https://termbin.com/x2shl

**Comment by PF4Public** [comment] 2020-11-30 11:57
Duplicate of #147

**Comment by p1u3o** [comment] 2020-11-30 11:59
You can use `flatpak override --user --share=network org.gnome.FontManager` as a work around for now.

**Comment by JerryCasiano** [comment] 2020-11-30 12:05
See https://github.com/flathub/org.gnome.FontManager/issues/4

Closing this out as it's not an application issue but a packaging issue.

@p1u3o 

Thanks for sharing that.

**Closed by JerryCasiano** 2020-11-30 12:05 UTC
Labels: duplicate

**Comment by mrmatteastwood** [comment] 2020-11-30 12:06
Thanks, guys! When executing `flatpak override --user --share=network org.gnome.FontManager` in the terminal, nothing happens. I'll just remain patient until a fix for this bug is out. :-)

**Comment by mrmatteastwood** [comment] 2020-11-30 12:12
Correction: when using p1u3o's command as the launch command for the menu entry in Mint Menu, it works! Thanks again!

**Comment by Eonfge** [comment] 2020-12-02 19:20
My apologies, I was not aware that such networking functionality was added to the project. Currently working on resolving it.

**Comment by JerryCasiano** [comment] 2020-12-02 19:25
@Eonfge 

Thanks for taking care of that.

Also... Sorry but some bugs cropped up in the latest release so I'll be doing another this evening.

If you could update the Flatpak to match once it's available that would be awesome.

**Comment by Eonfge** [comment] 2020-12-02 19:27
Ow, no problem. If you're working on a release right now, I'll distribute them at the same time
